version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: bookstore-backend

    ports:
      - "${PORT}:3000"

    environment:
      NODE_ENV: production

      PORT: ${PORT}

      # Neon DB
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    restart: always