version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: bookstore-backend

    ports:
      - "${PORT}:3000"

    env_file:
      - .env

    environment:
      NODE_ENV: production

    restart: unless-stopped